force-app/main/default/objects/Account/fields/PPSTN_ClientID__c.field-meta.xml
<CustomField>
    <fullName>PPSTN_ClientID__c</fullName>
    <externalId>true</externalId>
    <label>PPSTN_ClientID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PPSTN_COR__c.field-meta.xml
<CustomField>
    <fullName>PPSTN_COR__c</fullName>
    <label>PPSTN_COR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PPSTN_LegalEntityType__c.field-meta.xml
<CustomField>
    <fullName>PPSTN_LegalEntityType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PPSTN_LegalEntityType</label>
    <referenceTo>PPSTN_LegalEntityType__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PPSTN_License_Type_SF__c.field-meta.xml
<CustomField>
    <fullName>PPSTN_License_Type_SF__c</fullName>
    <label>PPSTN_License_Type_SF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASIC</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>SCB</fullName>
            </value>
            <value>
                <fullName>BAFIN</fullName>
            </value>
            <value>
                <fullName>CYSEC</fullName>
            </value>
            <value>
                <fullName>CMA</fullName>
            </value>
            <value>
                <fullName>DFSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPSTN_LegalEntityType__c/PPSTN_LegalEntityType__c.object-meta.xml
<CustomObject>
    <label>PPSTN_LegalEntityType</label>
    <nameField>
        <displayFormat>LET-{0000}</displayFormat>
        <label>SFLegalEntityType</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPSTN_LegalEntityTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountController.cls
/* Must ensure users have access to this Apex Class in the Security settings */
public with sharing class AccountController {

    /**
     * Assume that Apex methods provision immutable data, even if it's possible
     * to mutate the data today. It's a best practice to treat all data that a 
     * component receives as immutable. To mutate the data, make a shallow copy 
     * of the objects you want to mutate. It’s important to understand this concept 
     * when working with data.
     *
     * LWC STARTER KIT NOTE: This code is only provided as an example of how to
     * call Apex from LWC. Developers are highly encouraged to strictly
     * use Lightning Web Components for operations that can modify data while offline
     *
     * For more information, please visit:
     * https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.apex
     */
    @AuraEnabled(cacheable=true)
    public static List<Account> getAccountList() {
        return [
            SELECT
                Id,
                Name,
                PPSTN_License_Type_SF__c,
                PPSTN_LegalEntityType__c,
                PPSTN_COR__c,
                Type,
                PPSTN_ClientId__c
            FROM Account
            where PPSTN_ClientId__c != NULL
            ORDER BY CreatedDate DESC
            LIMIT 10
        ];
    }
}